management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Tanmoy123@
    url: jdbc:mysql://localhost:3306/nitredis
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 60000
